###~~~~~~ general settings ~~~~~~###

# sample meta data file
sample_tsv: "sample_fastq_list_paired.txt"

# sequencing config
layout: "paired"
#cutadapt_nextseq_flag: "--nextseq-trim=20"
cutadapt_nextseq_flag: ""

#############################################
# Pipeline scripts ##########################
#############################################
picard_build_script: "scripts/picard_ref_builder.sh"
featurecounts_rscript: "scripts/readcnt_to_rpkmtpm.py"
featurecounts_annscript: "scripts/add_gene_to_ensg.py"
pca_plot_script: "scripts/pca_plotting.py"

#############################################
# Software Paths for use with "--use-conda" #
############################################# 
cutadapt_path: "cutadapt"
samtools_path: "samtools"
aligner_path: "hisat2"
featurecounts_path: "featureCounts"
picard_path: "picard"
rsem_calc_exp_path: "rsem-calculate-expression"
rsem_prep_ref_path: "rsem-prepare-reference"
multiqc_path: "multiqc"
umi_tools_path: "umi_tools"

############################################# 
# Custom Software Paths #####################
############################################# 
java_path: "/usr/bin/java"

###~~~~~~ alignment settings ~~~~~~###
aligner_name: "hisat" #'hisat' or 'star'

###~~~~~~ quant settings ~~~~~~###
featurecounts_strand: "2" #1 for first read transcription strand, 2 for second.
run_rsem: "no"
rsem_strandedness: "unstranded"

###~~~~~~ other ~~~~~~###
picard_strand: "SECOND_READ_TRANSCRIPTION_STRAND"
#############################################
# Input reference fasta and GTF annotation ##
#############################################
reference_fa: "/dartfs/rc/nosnapshots/G/GMBSR_refs/Mmusculus/GRCm39/downloads/GRCm39.primary_assembly.genome.fa"
annotation_gtf: "/dartfs/rc/nosnapshots/G/GMBSR_refs/Mmusculus/GRCm39/downloads/gencode.vM34.annotation.gtf"


#############################################
# Aligner index and picard references #######
# create and specify these or ###############
# run snakemake build_ref rule to create ####
#############################################
aligner_index: '/dartfs/rc/nosnapshots/G/GMBSR_refs/Mmusculus/GRCm39/rna_index/hisat2_index/GRCm39.primary_assembly.genome'
picard_refflat: '/dartfs/rc/nosnapshots/G/GMBSR_refs/Mmusculus/GRCm39/annotation/picard/GRCm39.primary_assembly.genome.refFlat'
picard_rrna_list: '/dartfs/rc/nosnapshots/G/GMBSR_refs/Mmusculus/GRCm39/annotation/picard/GRCm39.primary_assembly.genome.rRNA.interval.list'
rsem_ref_path: '/dartfs/rc/nosnapshots/G/GMBSR_refs/Mmusculus/GRCm39/rna_index/RSEM_index/GRCm39.primary_assembly.genome'

